### PR TITLE
graphics

### PR DESCRIPTION
**Pull request by xvii-tommy**
latest for code review
some of your improvements done working on others.

### CODE REVIEW

**Comment by Adrir** [comment]
@James120393 - you commented on the earliest commit (aad0783) rather than the most recent commit (885a506). Did you look through the most recent code?

Generally happy with the new function names, with the exception of overlay1, 2, 3, etc.

**Comment by xvii-tommy** [comment]
Hi, I don't think I read through the most recent code of James I will do
this if the code I looked at was not tomorrow and fill out the forms and
send it to you.

With regards
Thomas

**Comment by Adrir** [comment]
Use the 'files changed' tab to get an overview of the whole program. Go into specific commits if you have already seen the previous version and am just checking the changes.

**Comment by xvii-tommy** [comment]
hi

I can no longer see a tinkering graphics pull request from james and dont
where to find the comp120 tinkering graphics on his github. Also is the
deadline for the tinkering audio and graphics the 18th.

with regards thomas

**Comment by Adrir** [comment]
Yes. The deadline is the 18th at 12 noon. This includes the programming projects and the reflective report.

**Comment by xvii-tommy** [comment]
hi,
i still cant find the james's tinkering graphics to review on his github
what should i do.

with regards

**Comment by Adrir** [comment]
It has likely been closed. You can continue to read and comment on closed pull requests, but you need to use [alternative search criteria](https://github.com/Falmouth-Games-Academy/comp120-tinkering-graphics/pulls?q=is%3Apr+is%3Aclosed).

When looking for pull requests, go to the original repository (in this case, the one created by Falmouth Games Academy). Select the pull requests tab. Select the text at the top which states 'closed'. This provides a list of all closed pull requests. Or, alternative, just change the search criteria in the filter box.

**Pull request closed without merging**
